# Generated by Django 6.0.1 on 2026-01-22 19:33

import django.db.models.deletion
import measure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheResponse',
            fields=[
                ('request', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('response', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default=measure.models.random_color, max_length=9)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', help_text='HTML permitido', verbose_name='descripción')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
            ],
            options={
                'verbose_name': 'línea/enfoque',
                'verbose_name_plural': 'líneas/enfoques',
            },
        ),
        migrations.CreateModel(
            name='LineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default=measure.models.random_color, max_length=9)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
            },
        ),
        migrations.CreateModel(
            name='MeasureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'detalle de medida',
                'verbose_name_plural': 'detalles de medidas',
            },
        ),
        migrations.CreateModel(
            name='Meta_0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('code',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default=measure.models.random_color, max_length=9)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'pilares',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default=measure.models.random_color, max_length=9)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', help_text='HTML permitido', verbose_name='descripción')),
                ('ingei', models.TextField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measure.line', verbose_name='línea/enfoque')),
            ],
            options={
                'verbose_name': 'línea de acción',
                'verbose_name_plural': 'Líneas de acción',
            },
        ),
        migrations.AddField(
            model_name='line',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measure.linecategory', verbose_name='categoría'),
        ),
        migrations.CreateModel(
            name='Meta_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(max_length=10)),
                ('meta_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measure.meta_0')),
            ],
            options={
                'ordering': ('code',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meta_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(max_length=10)),
                ('meta_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measure.meta_1')),
            ],
            options={
                'ordering': ('code',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='activa')),
                ('code', models.CharField(max_length=6, verbose_name='codigo')),
                ('year', models.IntegerField(default=2024, verbose_name='meta')),
                ('status', models.CharField(choices=[('En programación', 'En programación'), ('En implementación inicial', 'En implementación inicial'), ('En implementación avanzada', 'En implementación avanzada'), ('Completada', 'Completada'), ('A definir', 'A definir')], default='A definir', max_length=27, verbose_name='estado de implementación')),
                ('scope', models.CharField(choices=[('A definir', 'A definir'), ('Regional', 'Regional'), ('Nacional', 'Nacional')], default='A definir', max_length=10, verbose_name='alcance')),
                ('add_labels', models.TextField(blank=True, null=True, verbose_name='etiquetas de fila')),
                ('fields', models.JSONField(blank=True, null=True, verbose_name='datos internos')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measure_set', to='measure.action', verbose_name='línea de acción')),
                ('labels', models.ManyToManyField(blank=True, to='measure.label', verbose_name='pilares')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='measure.line', verbose_name='línea/enfoque')),
                ('national_objectives', models.ManyToManyField(blank=True, to='measure.meta_2', verbose_name='metas de adaptación')),
                ('pilares', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measure.pilar')),
            ],
            options={
                'verbose_name': 'medida',
            },
        ),
    ]
