# Generated by Django 6.0.1 on 2026-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_alter_measure_code_alter_measure_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='año')),
                ('title', models.CharField(blank=True, help_text='Opcional. Ej: "Reporte de Progreso 2024". Si está vacío se usa "Reporte de Progreso {año}".', max_length=200, verbose_name='título')),
                ('file', models.FileField(upload_to='measure/progress_reports', verbose_name='archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
            ],
            options={
                'verbose_name': 'reporte de progreso',
                'verbose_name_plural': 'reportes de progreso',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
