# Generated by Django 6.0.1 on 2026-02-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_name_255_implementation_status'),
        ('measure', '0004_progressreport'),
    ]

    operations = [
    ]
