# Generated by Django 6.0.1 on 2026-02-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0005_merge_20260204_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measures', to='measure.implementationstatus', verbose_name='estado de implementación'),
        ),
    ]
