# Generated by Django 6.0.1 on 2026-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0010_measureyearmeta_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Opcional. Ej: "Metodología del módulo de monitoreo".', max_length=200, verbose_name='título')),
                ('file', models.FileField(upload_to='measure/methodology', verbose_name='archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
            ],
            options={
                'verbose_name': 'documento de metodología',
                'verbose_name_plural': 'documentos de metodología',
                'ordering': ['-created_at'],
            },
        ),
    ]
