# Generated by Django 6.0.1 on 2026-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0012_fix_measure_status_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='show_alcance_estado',
            field=models.BooleanField(default=True, help_text='Mostrar bloque "Alcance y estado" en la ficha MYE.', verbose_name='mostrar Alcance y estado'),
        ),
        migrations.AddField(
            model_name='measure',
            name='show_alcance_geografico',
            field=models.BooleanField(default=True, help_text='Mostrar bloque "Alcance geográfico" en la ficha MYE.', verbose_name='mostrar Alcance geográfico'),
        ),
        migrations.AddField(
            model_name='measure',
            name='show_metas_por_ano',
            field=models.BooleanField(default=True, help_text='Mostrar bloque "Metas por año" en la ficha MYE.', verbose_name='mostrar Metas por año'),
        ),
        migrations.AddField(
            model_name='measure',
            name='show_periodo_meta',
            field=models.BooleanField(default=True, help_text='Mostrar bloque "Período meta" en la ficha MYE.', verbose_name='mostrar Período meta'),
        ),
        migrations.AddField(
            model_name='measure',
            name='show_riesgos_climaticos',
            field=models.BooleanField(default=True, help_text='Mostrar bloque "Riesgos climáticos" en la ficha MYE.', verbose_name='mostrar Riesgos climáticos'),
        ),
    ]
