URL_ORIGEN="https://inventariogei.ambiente.gob.ar/files"
DESTINO="./app/static/main/json"

# Descarga con overwrite

wget "$URL_ORIGEN"/monitoreo_1.json -O "${DESTINO}/monitoreo_1.json"
wget "$URL_ORIGEN"/monitoreo_2.json -O "${DESTINO}/monitoreo_2.json"
wget "$URL_ORIGEN"/monitoreo_3.json -O "${DESTINO}/monitoreo_3.json"
wget "$URL_ORIGEN"/monitoreo_4.json -O "${DESTINO}/monitoreo_4.json"
wget "$URL_ORIGEN"/monitoreo_5.json -O "${DESTINO}/monitoreo_5.json"
wget "$URL_ORIGEN"/monitoreo_6.json -O "${DESTINO}/monitoreo_6.json"
wget "$URL_ORIGEN"/monitoreo_7.json -O "${DESTINO}/monitoreo_7.json"
wget "$URL_ORIGEN"/monitoreo_8.json -O "${DESTINO}/monitoreo_8.json"
wget "$URL_ORIGEN"/monitoreo_9.json -O "${DESTINO}/monitoreo_9.json"
wget "$URL_ORIGEN"/monitoreo_10.json -O "${DESTINO}/monitoreo_10.json"
wget "$URL_ORIGEN"/monitoreo_11.json -O "${DESTINO}/monitoreo_11.json"
wget "$URL_ORIGEN"/monitoreo_12.json -O "${DESTINO}/monitoreo_12.json"
wget "$URL_ORIGEN"/monitoreo_13.json -O "${DESTINO}/monitoreo_13.json"
wget "$URL_ORIGEN"/monitoreo_14.json -O "${DESTINO}/monitoreo_14.json"
wget "$URL_ORIGEN"/monitoreo_15.json -O "${DESTINO}/monitoreo_15.json"
wget "$URL_ORIGEN"/monitoreo_16.json -O "${DESTINO}/monitoreo_16.json"
wget "$URL_ORIGEN"/monitoreo_17.json -O "${DESTINO}/monitoreo_17.json"
wget "$URL_ORIGEN"/monitoreo_18.json -O "${DESTINO}/monitoreo_18.json"
wget "$URL_ORIGEN"/monitoreo_19.json -O "${DESTINO}/monitoreo_19.json"
wget "$URL_ORIGEN"/monitoreo_20.json -O "${DESTINO}/monitoreo_20.json"
wget "$URL_ORIGEN"/monitoreo_21.json -O "${DESTINO}/monitoreo_21.json"
wget "$URL_ORIGEN"/monitoreo_22.json -O "${DESTINO}/monitoreo_22.json"
wget "$URL_ORIGEN"/monitoreo_23.json -O "${DESTINO}/monitoreo_23.json"
wget "$URL_ORIGEN"/monitoreo_24.json -O "${DESTINO}/monitoreo_24.json"
wget "$URL_ORIGEN"/monitoreo_25.json -O "${DESTINO}/monitoreo_25.json"
wget "$URL_ORIGEN"/monitoreo_26.json -O "${DESTINO}/monitoreo_26.json"
wget "$URL_ORIGEN"/monitoreo_27.json -O "${DESTINO}/monitoreo_27.json"
wget "$URL_ORIGEN"/monitoreo_28.json -O "${DESTINO}/monitoreo_28.json"
wget "$URL_ORIGEN"/monitoreo_29.json -O "${DESTINO}/monitoreo_29.json"
wget "$URL_ORIGEN"/monitoreo_30.json -O "${DESTINO}/monitoreo_30.json"
wget "$URL_ORIGEN"/monitoreo_31.json -O "${DESTINO}/monitoreo_31.json"
wget "$URL_ORIGEN"/monitoreo_32.json -O "${DESTINO}/monitoreo_32.json"
wget "$URL_ORIGEN"/monitoreo_33.json -O "${DESTINO}/monitoreo_33.json"
wget "$URL_ORIGEN"/monitoreo_34.json -O "${DESTINO}/monitoreo_34.json"
wget "$URL_ORIGEN"/monitoreo_35.json -O "${DESTINO}/monitoreo_35.json"
wget "$URL_ORIGEN"/monitoreo_36.json -O "${DESTINO}/monitoreo_36.json"
wget "$URL_ORIGEN"/monitoreo_37.json -O "${DESTINO}/monitoreo_37.json"
wget "$URL_ORIGEN"/monitoreo_38.json -O "${DESTINO}/monitoreo_38.json"
wget "$URL_ORIGEN"/monitoreo_39.json -O "${DESTINO}/monitoreo_39.json"
wget "$URL_ORIGEN"/monitoreo_40.json -O "${DESTINO}/monitoreo_40.json"
wget "$URL_ORIGEN"/monitoreo_41.json -O "${DESTINO}/monitoreo_41.json"
