# Generated by Django 6.0.1 on 2026-01-22 19:33

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('Adaptación', 'Adaptación'), ('Pérdidas y daños', 'Pérdidas y daños'), ('Mitigación', 'Mitigación'), ('Capacitacion', 'Capacitación'), ('Normativas', 'Normativas'), ('Adaptación, Pérdidas y daños', 'Adaptación y Pérdidas y daños'), ('Mitigación, Pérdidas y daños', 'Mitigación y Pérdidas y daños'), ('Adaptación, Mitigación', 'Adaptación y Mitigación'), ('Adaptación, Mitigación, Pérdidas y daños', 'Adaptación, Mitigación y Pérdidas y daños')], default='Adaptación, Mitigación, Pérdidas y daños', max_length=50)),
            ],
            options={
                'verbose_name': 'enlace de interés',
                'verbose_name_plural': 'enlace de interés',
            },
            bases=(models.Model, main.models.VersionedNoDate),
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='title')),
                ('view', models.CharField(blank=True, help_text='Exactly one of this or "url" must be set.', max_length=50, null=True)),
                ('viewargs', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, help_text='Exactly one of this or "view" must be set.', null=True)),
            ],
            bases=(models.Model, main.models.VersionedNoDate),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='código')),
                ('order', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'idioma',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'No presentado'), (2, 'En proceso de preconvalidación (análisis ANA-SsA)'), (3, 'En proceso de preconvalidación (análisis MAP-GNCC)'), (4, 'En proceso de preconvalidación'), (5, 'Convalidado')], default=1)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'planes',
            },
            bases=(models.Model, main.models.VersionedNoDate),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('hidden', models.BooleanField(blank=True, default=False, verbose_name='oculto')),
                ('image', models.FileField(null=True, upload_to='profile')),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('specific_url', models.CharField(blank=True, help_text='relevant post slug', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('gid', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='código')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linktype', models.CharField(choices=[('Decreto', 'Decreto'), ('Ley', 'Ley'), ('Decisiones administrativas', 'Administrativo'), ('Resolucion', 'Resolucion')], default='Ley', max_length=30)),
                ('url', models.URLField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'normativa',
                'verbose_name_plural': 'normativas',
            },
            bases=(models.Model, main.models.VersionedNoDate),
        ),
        migrations.CreateModel(
            name='RegulationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es', models.TextField(unique=True, verbose_name='Español')),
            ],
            options={
                'verbose_name': 'traducción estática',
                'verbose_name_plural': 'traducciones estáticas',
            },
            bases=(models.Model, main.models.Versioned),
        ),
        migrations.CreateModel(
            name='StaticTransVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('category', models.CharField(choices=[('Adaptación', 'Adaptación'), ('Pérdidas y daños', 'Pérdidas y daños'), ('Mitigación', 'Mitigación'), ('Capacitacion', 'Capacitación'), ('Normativas', 'Normativas'), ('Adaptación, Pérdidas y daños', 'Adaptación y Pérdidas y daños'), ('Mitigación, Pérdidas y daños', 'Mitigación y Pérdidas y daños'), ('Adaptación, Mitigación', 'Adaptación y Mitigación'), ('Adaptación, Mitigación, Pérdidas y daños', 'Adaptación, Mitigación y Pérdidas y daños')], default='Adaptación, Mitigación, Pérdidas y daños', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='books')),
                ('comunidad', models.BooleanField(blank=True, default=False)),
                ('capacitaciones', models.BooleanField(blank=True, default=False)),
                ('ciudadania', models.BooleanField(blank=True, default=False)),
                ('format', models.CharField(choices=[('Documento', 'Documento'), ('Infografía', 'Infografia')], max_length=20, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='main.author')),
            ],
            options={
                'verbose_name': 'libro',
            },
            bases=(models.Model, main.models.VersionedNoDate),
        ),
        migrations.CreateModel(
            name='InternalLinkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.TextField(blank=True, help_text='Descripción breve, 500 caracteres como máximo', null=True, verbose_name='texto de la tarjeta')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.internallink')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLinkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.externallink')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='BookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.book')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.TextField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('regulations', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'novedad'), (2, 'recurso')], default=2, help_text='Las publicaciones establecidas como "novedad" aparecerán en la sección de novedades, la más reciente primero.', verbose_name='typo')),
                ('category', models.CharField(choices=[('Adaptación', 'Adaptación'), ('Pérdidas y daños', 'Pérdidas y daños'), ('Mitigación', 'Mitigación'), ('Capacitacion', 'Capacitación'), ('Normativas', 'Normativas'), ('Adaptación, Pérdidas y daños', 'Adaptación y Pérdidas y daños'), ('Mitigación, Pérdidas y daños', 'Mitigación y Pérdidas y daños'), ('Adaptación, Mitigación', 'Adaptación y Mitigación'), ('Adaptación, Mitigación, Pérdidas y daños', 'Adaptación, Mitigación y Pérdidas y daños')], default='Adaptación, Mitigación, Pérdidas y daños', max_length=50, verbose_name='categoria')),
                ('slug', models.SlugField(help_text='autoset', max_length=30, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'borrador'), (2, 'publicado')], default=1, verbose_name='estado')),
                ('image', models.FileField(blank=True, null=True, upload_to='title', verbose_name='imagen')),
                ('date', models.DateTimeField(auto_now=True)),
                ('protected', models.BooleanField(blank=True, default=False, help_text='Special post, should never be deleted.')),
                ('parent', models.ForeignKey(blank=True, help_text='solo para recursos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.post', verbose_name='padre')),
            ],
            options={
                'verbose_name': 'recurso/novedad',
                'verbose_name_plural': 'recursos/novedades',
            },
            bases=(models.Model, main.models.Versioned),
        ),
        migrations.AddField(
            model_name='internallink',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.post'),
        ),
        migrations.CreateModel(
            name='BookReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.book')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.post')),
            ],
            options={
                'verbose_name': 'Documentación complementaria',
                'verbose_name_plural': 'Documentación complementaria',
                'ordering': ['book'],
            },
        ),
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('body', models.TextField(blank=True, null=True, verbose_name='texto')),
                ('date', models.DateTimeField(auto_now=True)),
                ('short', models.CharField(blank=True, help_text='Descripción breve, 500 caracteres como máximo', max_length=500, null=True, verbose_name='texto de la tarjeta')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
