# Generated by Django 6.0.1 on 2026-01-22 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='main.profile'),
        ),
        migrations.AddField(
            model_name='plan',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provincia'),
        ),
        migrations.AddField(
            model_name='regulationversion',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
        migrations.AddField(
            model_name='regulationversion',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.regulation'),
        ),
        migrations.AddField(
            model_name='statictransversion',
            name='es',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.statictrans'),
        ),
        migrations.AddField(
            model_name='statictransversion',
            name='lang',
            field=models.ForeignKey(limit_choices_to=models.Q(('code', 'es'), _negated=True), on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
        migrations.AlterUniqueTogether(
            name='internallinkversion',
            unique_together={('lang', 'link')},
        ),
        migrations.AlterUniqueTogether(
            name='externallinkversion',
            unique_together={('lang', 'link')},
        ),
        migrations.AlterUniqueTogether(
            name='bookversion',
            unique_together={('lang', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together={('lang', 'plan')},
        ),
        migrations.AlterUniqueTogether(
            name='postprofile',
            unique_together={('profile', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='statictransversion',
            unique_together={('lang', 'es')},
        ),
    ]
