# Generated by Django 6.0.1 on 2026-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(blank=True, help_text='PDF o Word (.doc, .docx). Opcional si se indica enlace externo.', null=True, upload_to='books/documents', verbose_name='Archivo (PDF o Word)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.IntegerField(choices=[(1, 'No presentado'), (2, 'En proceso de preconvalidación (análisis ANA-SsA)'), (3, 'En proceso de preconvalidación (análisis MAP-GNCC)'), (4, 'En proceso de convalidación'), (5, 'Convalidado')], default=1),
        ),
    ]
