# Generated by Django 6.0.1 on 2026-02-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookformat_remove_book_format_book_format_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'suscripción a novedades',
                'verbose_name_plural': 'suscripciones a novedades',
            },
        ),
    ]
